name: flutter_i18n_manager
description: Flutter i18n Manager
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  file_picker: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  generate: true
  uses-material-design: true